//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.10 at 07:14:25 PM IRDT 
//


package com.asgarie.ClaimSender.entity.model.entity.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ResultVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResultVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MessageUID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ErrorMessage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CompositionUID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="patientUID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResultVO", propOrder = {
    "messageUID",
    "errorMessage",
    "compositionUID",
    "patientUID"
})
public class ResultVO {

    @XmlElement(name = "MessageUID")
    protected String messageUID;
    @XmlElement(name = "ErrorMessage")
    protected String errorMessage;
    @XmlElement(name = "CompositionUID")
    protected String compositionUID;
    protected String patientUID;

    /**
     * Gets the value of the messageUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageUID() {
        return messageUID;
    }

    /**
     * Sets the value of the messageUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageUID(String value) {
        this.messageUID = value;
    }

    /**
     * Gets the value of the errorMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorMessage() {
        return errorMessage;
    }

    /**
     * Sets the value of the errorMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorMessage(String value) {
        this.errorMessage = value;
    }

    /**
     * Gets the value of the compositionUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompositionUID() {
        return compositionUID;
    }

    /**
     * Sets the value of the compositionUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompositionUID(String value) {
        this.compositionUID = value;
    }

    /**
     * Gets the value of the patientUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatientUID() {
        return patientUID;
    }

    /**
     * Sets the value of the patientUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatientUID(String value) {
        this.patientUID = value;
    }

}
