//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.10 at 07:14:25 PM IRDT 
//


package ir.demisco.model.entity.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SavePatientBillResult" type="{http://thrita.behdasht.gov.ir/VM}ResultVO" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "savePatientBillResult"
})
@XmlRootElement(name = "SavePatientBillResponse")
public class SavePatientBillResponse {

    @XmlElement(name = "SavePatientBillResult")
    protected ResultVO savePatientBillResult;

    /**
     * Gets the value of the savePatientBillResult property.
     * 
     * @return
     *     possible object is
     *     {@link ResultVO }
     *     
     */
    public ResultVO getSavePatientBillResult() {
        return savePatientBillResult;
    }

    /**
     * Sets the value of the savePatientBillResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResultVO }
     *     
     */
    public void setSavePatientBillResult(ResultVO value) {
        this.savePatientBillResult = value;
    }

}
