
package com.asgarie.ClaimSender.entity.ws.behdasht.sepas;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;

;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "BillPatientApi", targetNamespace = "http://sepas.behdasht.gov.ir/", wsdlLocation = "https://iehr.ihio.gov.ir/BillPatient/BillPatientPort?WSDL")
public class BillPatientService
        extends Service
{

    private final static URL BILLPATIENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException BILLPATIENTSERVICE_EXCEPTION;
    private final static QName BILLPATIENTSERVICE_QNAME = new QName("http://sepas.behdasht.gov.ir/", "BillPatientService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://iehr.ihio.gov.ir/BillPatient/BillPatientPort?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BILLPATIENTSERVICE_WSDL_LOCATION = url;
        BILLPATIENTSERVICE_EXCEPTION = e;
    }

    public BillPatientService() {
        super(__getWsdlLocation(), BILLPATIENTSERVICE_QNAME);
    }

    public BillPatientService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BILLPATIENTSERVICE_QNAME, features);
    }

    public BillPatientService(URL wsdlLocation) {
        super(wsdlLocation, BILLPATIENTSERVICE_QNAME);
    }

    public BillPatientService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BILLPATIENTSERVICE_QNAME, features);
    }

    public BillPatientService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BillPatientService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns BillPatient
     */
    @WebEndpoint(name = "BillPatientPort")
    public BillPatient getBillPatientPort() {
        return super.getPort(new QName("http://sepas.behdasht.gov.ir/", "BillPatientPort"), BillPatient.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BillPatient
     */
    @WebEndpoint(name = "BillPatientPort")
    public BillPatient getBillPatientPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://sepas.behdasht.gov.ir/", "BillPatientPort"), BillPatient.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BILLPATIENTSERVICE_EXCEPTION!= null) {
            throw BILLPATIENTSERVICE_EXCEPTION;
        }
        return BILLPATIENTSERVICE_WSDL_LOCATION;
    }

}
