
package com.asgarie.ClaimSender.entity.ws.behdasht.sepas;

import com.asgarie.ClaimSender.entity.ws.behdasht.thrita.vm.ResultVO;
import com.asgarie.ClaimSender.entity.ws.behdasht.thrita.vm.ObjectFactory;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "BillPatient", targetNamespace = "http://sepas.behdasht.gov.ir/")
@XmlSeeAlso({
        ObjectFactory.class,
        ObjectFactory.class
})
public interface BillPatient {


    /**
     * @param patientBillMessageVO
     * @return returns ir.gov.behdasht.thrita.vm.ResultVO
     */
    @WebMethod
    @WebResult(name = "ResultVO", targetNamespace = "")
    @RequestWrapper(localName = "savePatientBill", targetNamespace = "http://sepas.behdasht.gov.ir/", className = "ir.gov.behdasht.sepas.SavePatientBill")
    @ResponseWrapper(localName = "savePatientBillResponse", targetNamespace = "http://sepas.behdasht.gov.ir/", className = "ir.gov.behdasht.sepas.SavePatientBillResponse")
    @Action(input = "http://sepas.behdasht.gov.ir/BillPatient/savePatientBillRequest", output = "http://sepas.behdasht.gov.ir/BillPatient/savePatientBillResponse")
    public ResultVO savePatientBill(
            @WebParam(name = "PatientBillMessageVO", targetNamespace = "")
                    PatientBillMessageVO patientBillMessageVO);

}
