//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.11 at 05:06:35 AM IRDT 
//


package com.asgarie.ClaimSender.entity.model.entity.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AdmissionVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AdmissionVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EMSID" type="{http://thrita.behdasht.gov.ir/VM}DO_IDENTIFIER" minOccurs="0" form="qualified"/>
 *         &lt;element name="OtherDateTime" type="{http://thrita.behdasht.gov.ir/VM}ArrayOfDateTimePointVO" minOccurs="0" form="qualified"/>
 *         &lt;element name="AdmissionDate" type="{http://thrita.behdasht.gov.ir/VM}DO_DATE" minOccurs="0" form="qualified"/>
 *         &lt;element name="AdmissionTime" type="{http://thrita.behdasht.gov.ir/VM}DO_TIME" minOccurs="0" form="qualified"/>
 *         &lt;element name="AdmissionType" type="{http://thrita.behdasht.gov.ir/VM}DO_CODED_TEXT" minOccurs="0" form="qualified"/>
 *         &lt;element name="MedicalRecordNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0" form="qualified"/>
 *         &lt;element name="Institute" type="{http://thrita.behdasht.gov.ir/VM}OrganizationVO" minOccurs="0" form="qualified"/>
 *         &lt;element name="ReasonForEncounter" type="{http://thrita.behdasht.gov.ir/VM}DO_CODED_TEXT" minOccurs="0" form="qualified"/>
 *         &lt;element name="AdmittingDoctor" type="{http://thrita.behdasht.gov.ir/VM}HealthcareProviderVO" minOccurs="0" form="qualified"/>
 *         &lt;element name="ReferringDoctor" type="{http://thrita.behdasht.gov.ir/VM}HealthcareProviderVO" minOccurs="0" form="qualified"/>
 *         &lt;element name="AttendingDoctor" type="{http://thrita.behdasht.gov.ir/VM}HealthcareProviderVO" minOccurs="0" form="qualified"/>
 *         &lt;element name="AdmissionWard" type="{http://thrita.behdasht.gov.ir/VM}HospitalWardVO" minOccurs="0" form="qualified"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AdmissionVO", propOrder = {
    "emsid",
    "otherDateTime",
    "admissionDate",
    "admissionTime",
    "admissionType",
    "medicalRecordNumber",
    "institute",
    "reasonForEncounter",
    "admittingDoctor",
    "referringDoctor",
    "attendingDoctor",
    "admissionWard"
})
public class AdmissionVO {

    @XmlElement(name = "EMSID")
    protected DOIDENTIFIER emsid;
    @XmlElement(name = "OtherDateTime")
    protected ArrayOfDateTimePointVO otherDateTime;
    @XmlElement(name = "AdmissionDate")
    protected DODATE admissionDate;
    @XmlElement(name = "AdmissionTime")
    protected DOTIME admissionTime;
    @XmlElement(name = "AdmissionType")
    protected DOCODEDTEXT admissionType;
    @XmlElement(name = "MedicalRecordNumber")
    protected String medicalRecordNumber;
    @XmlElement(name = "Institute")
    protected OrganizationVO institute;
    @XmlElement(name = "ReasonForEncounter")
    protected DOCODEDTEXT reasonForEncounter;
    @XmlElement(name = "AdmittingDoctor")
    protected HealthcareProviderVO admittingDoctor;
    @XmlElement(name = "ReferringDoctor")
    protected HealthcareProviderVO referringDoctor;
    @XmlElement(name = "AttendingDoctor")
    protected HealthcareProviderVO attendingDoctor;
    @XmlElement(name = "AdmissionWard")
    protected HospitalWardVO admissionWard;

    /**
     * Gets the value of the emsid property.
     * 
     * @return
     *     possible object is
     *     {@link DOIDENTIFIER }
     *     
     */
    public DOIDENTIFIER getEMSID() {
        return emsid;
    }

    /**
     * Sets the value of the emsid property.
     * 
     * @param value
     *     allowed object is
     *     {@link DOIDENTIFIER }
     *     
     */
    public void setEMSID(DOIDENTIFIER value) {
        this.emsid = value;
    }

    /**
     * Gets the value of the otherDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfDateTimePointVO }
     *     
     */
    public ArrayOfDateTimePointVO getOtherDateTime() {
        return otherDateTime;
    }

    /**
     * Sets the value of the otherDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfDateTimePointVO }
     *     
     */
    public void setOtherDateTime(ArrayOfDateTimePointVO value) {
        this.otherDateTime = value;
    }

    /**
     * Gets the value of the admissionDate property.
     * 
     * @return
     *     possible object is
     *     {@link DODATE }
     *     
     */
    public DODATE getAdmissionDate() {
        return admissionDate;
    }

    /**
     * Sets the value of the admissionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DODATE }
     *     
     */
    public void setAdmissionDate(DODATE value) {
        this.admissionDate = value;
    }

    /**
     * Gets the value of the admissionTime property.
     * 
     * @return
     *     possible object is
     *     {@link DOTIME }
     *     
     */
    public DOTIME getAdmissionTime() {
        return admissionTime;
    }

    /**
     * Sets the value of the admissionTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link DOTIME }
     *     
     */
    public void setAdmissionTime(DOTIME value) {
        this.admissionTime = value;
    }

    /**
     * Gets the value of the admissionType property.
     * 
     * @return
     *     possible object is
     *     {@link DOCODEDTEXT }
     *     
     */
    public DOCODEDTEXT getAdmissionType() {
        return admissionType;
    }

    /**
     * Sets the value of the admissionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link DOCODEDTEXT }
     *     
     */
    public void setAdmissionType(DOCODEDTEXT value) {
        this.admissionType = value;
    }

    /**
     * Gets the value of the medicalRecordNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMedicalRecordNumber() {
        return medicalRecordNumber;
    }

    /**
     * Sets the value of the medicalRecordNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMedicalRecordNumber(String value) {
        this.medicalRecordNumber = value;
    }

    /**
     * Gets the value of the institute property.
     * 
     * @return
     *     possible object is
     *     {@link OrganizationVO }
     *     
     */
    public OrganizationVO getInstitute() {
        return institute;
    }

    /**
     * Sets the value of the institute property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrganizationVO }
     *     
     */
    public void setInstitute(OrganizationVO value) {
        this.institute = value;
    }

    /**
     * Gets the value of the reasonForEncounter property.
     * 
     * @return
     *     possible object is
     *     {@link DOCODEDTEXT }
     *     
     */
    public DOCODEDTEXT getReasonForEncounter() {
        return reasonForEncounter;
    }

    /**
     * Sets the value of the reasonForEncounter property.
     * 
     * @param value
     *     allowed object is
     *     {@link DOCODEDTEXT }
     *     
     */
    public void setReasonForEncounter(DOCODEDTEXT value) {
        this.reasonForEncounter = value;
    }

    /**
     * Gets the value of the admittingDoctor property.
     * 
     * @return
     *     possible object is
     *     {@link HealthcareProviderVO }
     *     
     */
    public HealthcareProviderVO getAdmittingDoctor() {
        return admittingDoctor;
    }

    /**
     * Sets the value of the admittingDoctor property.
     * 
     * @param value
     *     allowed object is
     *     {@link HealthcareProviderVO }
     *     
     */
    public void setAdmittingDoctor(HealthcareProviderVO value) {
        this.admittingDoctor = value;
    }

    /**
     * Gets the value of the referringDoctor property.
     * 
     * @return
     *     possible object is
     *     {@link HealthcareProviderVO }
     *     
     */
    public HealthcareProviderVO getReferringDoctor() {
        return referringDoctor;
    }

    /**
     * Sets the value of the referringDoctor property.
     * 
     * @param value
     *     allowed object is
     *     {@link HealthcareProviderVO }
     *     
     */
    public void setReferringDoctor(HealthcareProviderVO value) {
        this.referringDoctor = value;
    }

    /**
     * Gets the value of the attendingDoctor property.
     * 
     * @return
     *     possible object is
     *     {@link HealthcareProviderVO }
     *     
     */
    public HealthcareProviderVO getAttendingDoctor() {
        return attendingDoctor;
    }

    /**
     * Sets the value of the attendingDoctor property.
     * 
     * @param value
     *     allowed object is
     *     {@link HealthcareProviderVO }
     *     
     */
    public void setAttendingDoctor(HealthcareProviderVO value) {
        this.attendingDoctor = value;
    }

    /**
     * Gets the value of the admissionWard property.
     * 
     * @return
     *     possible object is
     *     {@link HospitalWardVO }
     *     
     */
    public HospitalWardVO getAdmissionWard() {
        return admissionWard;
    }

    /**
     * Sets the value of the admissionWard property.
     * 
     * @param value
     *     allowed object is
     *     {@link HospitalWardVO }
     *     
     */
    public void setAdmissionWard(HospitalWardVO value) {
        this.admissionWard = value;
    }

}
