//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.11 at 05:06:35 AM IRDT 
//


package com.asgarie.ClaimSender.entity.model.entity.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BillSummaryVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BillSummaryVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TotalOtherCosts" type="{http://thrita.behdasht.gov.ir/VM}ArrayOfQuantitiesVO" minOccurs="0" form="qualified"/>
 *         &lt;element name="Insurer" type="{http://thrita.behdasht.gov.ir/VM}DO_CODED_TEXT" minOccurs="0" form="qualified"/>
 *         &lt;element name="InsurerBox" type="{http://thrita.behdasht.gov.ir/VM}DO_CODED_TEXT" minOccurs="0" form="qualified"/>
 *         &lt;element name="TotalBasicInsuranceContribution" type="{http://thrita.behdasht.gov.ir/VM}DO_QUANTITY" minOccurs="0" form="qualified"/>
 *         &lt;element name="HospitalAccreditation" type="{http://www.w3.org/2001/XMLSchema}int" form="qualified"/>
 *         &lt;element name="MedicalRecordType" type="{http://thrita.behdasht.gov.ir/VM}DO_CODED_TEXT" minOccurs="0" form="qualified"/>
 *         &lt;element name="GlobalPackage" type="{http://thrita.behdasht.gov.ir/VM}DO_CODED_TEXT" minOccurs="0" form="qualified"/>
 *         &lt;element name="TotalPatientContribution" type="{http://thrita.behdasht.gov.ir/VM}DO_QUANTITY" minOccurs="0" form="qualified"/>
 *         &lt;element name="TotalCharge" type="{http://thrita.behdasht.gov.ir/VM}DO_QUANTITY" minOccurs="0" form="qualified"/>
 *         &lt;element name="ServiceGroupRow" type="{http://thrita.behdasht.gov.ir/VM}ArrayOfServiceGroupRowVO" minOccurs="0" form="qualified"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BillSummaryVO", propOrder = {
    "totalOtherCosts",
    "insurer",
    "insurerBox",
    "totalBasicInsuranceContribution",
    "hospitalAccreditation",
    "medicalRecordType",
    "globalPackage",
    "totalPatientContribution",
    "totalCharge",
    "serviceGroupRow"
})
public class BillSummaryVO {

    @XmlElement(name = "TotalOtherCosts")
    protected ArrayOfQuantitiesVO totalOtherCosts;
    @XmlElement(name = "Insurer")
    protected DOCODEDTEXT insurer;
    @XmlElement(name = "InsurerBox")
    protected DOCODEDTEXT insurerBox;
    @XmlElement(name = "TotalBasicInsuranceContribution")
    protected DOQUANTITY totalBasicInsuranceContribution;
    @XmlElement(name = "HospitalAccreditation")
    protected int hospitalAccreditation;
    @XmlElement(name = "MedicalRecordType")
    protected DOCODEDTEXT medicalRecordType;
    @XmlElement(name = "GlobalPackage")
    protected DOCODEDTEXT globalPackage;
    @XmlElement(name = "TotalPatientContribution")
    protected DOQUANTITY totalPatientContribution;
    @XmlElement(name = "TotalCharge")
    protected DOQUANTITY totalCharge;
    @XmlElement(name = "ServiceGroupRow")
    protected ArrayOfServiceGroupRowVO serviceGroupRow;

    /**
     * Gets the value of the totalOtherCosts property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfQuantitiesVO }
     *     
     */
    public ArrayOfQuantitiesVO getTotalOtherCosts() {
        return totalOtherCosts;
    }

    /**
     * Sets the value of the totalOtherCosts property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfQuantitiesVO }
     *     
     */
    public void setTotalOtherCosts(ArrayOfQuantitiesVO value) {
        this.totalOtherCosts = value;
    }

    /**
     * Gets the value of the insurer property.
     * 
     * @return
     *     possible object is
     *     {@link DOCODEDTEXT }
     *     
     */
    public DOCODEDTEXT getInsurer() {
        return insurer;
    }

    /**
     * Sets the value of the insurer property.
     * 
     * @param value
     *     allowed object is
     *     {@link DOCODEDTEXT }
     *     
     */
    public void setInsurer(DOCODEDTEXT value) {
        this.insurer = value;
    }

    /**
     * Gets the value of the insurerBox property.
     * 
     * @return
     *     possible object is
     *     {@link DOCODEDTEXT }
     *     
     */
    public DOCODEDTEXT getInsurerBox() {
        return insurerBox;
    }

    /**
     * Sets the value of the insurerBox property.
     * 
     * @param value
     *     allowed object is
     *     {@link DOCODEDTEXT }
     *     
     */
    public void setInsurerBox(DOCODEDTEXT value) {
        this.insurerBox = value;
    }

    /**
     * Gets the value of the totalBasicInsuranceContribution property.
     * 
     * @return
     *     possible object is
     *     {@link DOQUANTITY }
     *     
     */
    public DOQUANTITY getTotalBasicInsuranceContribution() {
        return totalBasicInsuranceContribution;
    }

    /**
     * Sets the value of the totalBasicInsuranceContribution property.
     * 
     * @param value
     *     allowed object is
     *     {@link DOQUANTITY }
     *     
     */
    public void setTotalBasicInsuranceContribution(DOQUANTITY value) {
        this.totalBasicInsuranceContribution = value;
    }

    /**
     * Gets the value of the hospitalAccreditation property.
     * 
     */
    public int getHospitalAccreditation() {
        return hospitalAccreditation;
    }

    /**
     * Sets the value of the hospitalAccreditation property.
     * 
     */
    public void setHospitalAccreditation(int value) {
        this.hospitalAccreditation = value;
    }

    /**
     * Gets the value of the medicalRecordType property.
     * 
     * @return
     *     possible object is
     *     {@link DOCODEDTEXT }
     *     
     */
    public DOCODEDTEXT getMedicalRecordType() {
        return medicalRecordType;
    }

    /**
     * Sets the value of the medicalRecordType property.
     * 
     * @param value
     *     allowed object is
     *     {@link DOCODEDTEXT }
     *     
     */
    public void setMedicalRecordType(DOCODEDTEXT value) {
        this.medicalRecordType = value;
    }

    /**
     * Gets the value of the globalPackage property.
     * 
     * @return
     *     possible object is
     *     {@link DOCODEDTEXT }
     *     
     */
    public DOCODEDTEXT getGlobalPackage() {
        return globalPackage;
    }

    /**
     * Sets the value of the globalPackage property.
     * 
     * @param value
     *     allowed object is
     *     {@link DOCODEDTEXT }
     *     
     */
    public void setGlobalPackage(DOCODEDTEXT value) {
        this.globalPackage = value;
    }

    /**
     * Gets the value of the totalPatientContribution property.
     * 
     * @return
     *     possible object is
     *     {@link DOQUANTITY }
     *     
     */
    public DOQUANTITY getTotalPatientContribution() {
        return totalPatientContribution;
    }

    /**
     * Sets the value of the totalPatientContribution property.
     * 
     * @param value
     *     allowed object is
     *     {@link DOQUANTITY }
     *     
     */
    public void setTotalPatientContribution(DOQUANTITY value) {
        this.totalPatientContribution = value;
    }

    /**
     * Gets the value of the totalCharge property.
     * 
     * @return
     *     possible object is
     *     {@link DOQUANTITY }
     *     
     */
    public DOQUANTITY getTotalCharge() {
        return totalCharge;
    }

    /**
     * Sets the value of the totalCharge property.
     * 
     * @param value
     *     allowed object is
     *     {@link DOQUANTITY }
     *     
     */
    public void setTotalCharge(DOQUANTITY value) {
        this.totalCharge = value;
    }

    /**
     * Gets the value of the serviceGroupRow property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfServiceGroupRowVO }
     *     
     */
    public ArrayOfServiceGroupRowVO getServiceGroupRow() {
        return serviceGroupRow;
    }

    /**
     * Sets the value of the serviceGroupRow property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfServiceGroupRowVO }
     *     
     */
    public void setServiceGroupRow(ArrayOfServiceGroupRowVO value) {
        this.serviceGroupRow = value;
    }

}
