//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.11 at 05:06:35 AM IRDT 
//


package com.asgarie.ClaimSender.entity.model.entity.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PersonInfoVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PersonInfoVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OtherIdentifier" type="{http://thrita.behdasht.gov.ir/VM}ArrayOfDO_IDENTIFIER" minOccurs="0" form="qualified"/>
 *         &lt;element name="BirthPlaceArea" type="{http://thrita.behdasht.gov.ir/VM}HighLevelAreaVO" minOccurs="0" form="qualified"/>
 *         &lt;element name="Religion" type="{http://thrita.behdasht.gov.ir/VM}DO_CODED_TEXT" minOccurs="0" form="qualified"/>
 *         &lt;element name="MaritalStatus" type="{http://thrita.behdasht.gov.ir/VM}DO_CODED_TEXT" minOccurs="0" form="qualified"/>
 *         &lt;element name="Nationality" type="{http://thrita.behdasht.gov.ir/VM}DO_CODED_TEXT" minOccurs="0" form="qualified"/>
 *         &lt;element name="BirthDate" type="{http://thrita.behdasht.gov.ir/VM}DO_DATE" minOccurs="0" form="qualified"/>
 *         &lt;element name="BirthTime" type="{http://thrita.behdasht.gov.ir/VM}DO_TIME" minOccurs="0" form="qualified"/>
 *         &lt;element name="BirthdateAccuracy" type="{http://thrita.behdasht.gov.ir/VM}DO_CODED_TEXT" minOccurs="0" form="qualified"/>
 *         &lt;element name="Father_FirstName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0" form="qualified"/>
 *         &lt;element name="Father_LastName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0" form="qualified"/>
 *         &lt;element name="Mother_FirstName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0" form="qualified"/>
 *         &lt;element name="Mother_LastName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0" form="qualified"/>
 *         &lt;element name="FullName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0" form="qualified"/>
 *         &lt;element name="PostalCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0" form="qualified"/>
 *         &lt;element name="Gender" type="{http://thrita.behdasht.gov.ir/VM}DO_CODED_TEXT" minOccurs="0" form="qualified"/>
 *         &lt;element name="Job" type="{http://thrita.behdasht.gov.ir/VM}DO_CODED_TEXT" minOccurs="0" form="qualified"/>
 *         &lt;element name="JobDescribtion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0" form="qualified"/>
 *         &lt;element name="FullAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0" form="qualified"/>
 *         &lt;element name="LivingPlaceArea" type="{http://thrita.behdasht.gov.ir/VM}HighLevelAreaVO" minOccurs="0" form="qualified"/>
 *         &lt;element name="IDCardNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0" form="qualified"/>
 *         &lt;element name="IDIssueArea" type="{http://thrita.behdasht.gov.ir/VM}HighLevelAreaVO" minOccurs="0" form="qualified"/>
 *         &lt;element name="HomeTel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0" form="qualified"/>
 *         &lt;element name="MobileNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0" form="qualified"/>
 *         &lt;element name="EducationLevel" type="{http://thrita.behdasht.gov.ir/VM}DO_CODED_TEXT" minOccurs="0" form="qualified"/>
 *       &lt;/sequence>
 *       &lt;attribute name="FirstName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="LastName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="NationalCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PersonInfoVO", propOrder = {
    "otherIdentifier",
    "birthPlaceArea",
    "religion",
    "maritalStatus",
    "nationality",
    "birthDate",
    "birthTime",
    "birthdateAccuracy",
    "fatherFirstName",
    "fatherLastName",
    "motherFirstName",
    "motherLastName",
    "fullName",
    "postalCode",
    "gender",
    "job",
    "jobDescribtion",
    "fullAddress",
    "livingPlaceArea",
    "idCardNumber",
    "idIssueArea",
    "homeTel",
    "mobileNumber",
    "educationLevel"
})
public class PersonInfoVO {

    @XmlElement(name = "OtherIdentifier")
    protected ArrayOfDOIDENTIFIER otherIdentifier;
    @XmlElement(name = "BirthPlaceArea")
    protected HighLevelAreaVO birthPlaceArea;
    @XmlElement(name = "Religion")
    protected DOCODEDTEXT religion;
    @XmlElement(name = "MaritalStatus")
    protected DOCODEDTEXT maritalStatus;
    @XmlElement(name = "Nationality")
    protected DOCODEDTEXT nationality;
    @XmlElement(name = "BirthDate")
    protected DODATE birthDate;
    @XmlElement(name = "BirthTime")
    protected DOTIME birthTime;
    @XmlElement(name = "BirthdateAccuracy")
    protected DOCODEDTEXT birthdateAccuracy;
    @XmlElement(name = "Father_FirstName")
    protected String fatherFirstName;
    @XmlElement(name = "Father_LastName")
    protected String fatherLastName;
    @XmlElement(name = "Mother_FirstName")
    protected String motherFirstName;
    @XmlElement(name = "Mother_LastName")
    protected String motherLastName;
    @XmlElement(name = "FullName")
    protected String fullName;
    @XmlElement(name = "PostalCode")
    protected String postalCode;
    @XmlElement(name = "Gender")
    protected DOCODEDTEXT gender;
    @XmlElement(name = "Job")
    protected DOCODEDTEXT job;
    @XmlElement(name = "JobDescribtion")
    protected String jobDescribtion;
    @XmlElement(name = "FullAddress")
    protected String fullAddress;
    @XmlElement(name = "LivingPlaceArea")
    protected HighLevelAreaVO livingPlaceArea;
    @XmlElement(name = "IDCardNumber")
    protected String idCardNumber;
    @XmlElement(name = "IDIssueArea")
    protected HighLevelAreaVO idIssueArea;
    @XmlElement(name = "HomeTel")
    protected String homeTel;
    @XmlElement(name = "MobileNumber")
    protected String mobileNumber;
    @XmlElement(name = "EducationLevel")
    protected DOCODEDTEXT educationLevel;
    @XmlAttribute(name = "FirstName")
    protected String firstName;
    @XmlAttribute(name = "LastName")
    protected String lastName;
    @XmlAttribute(name = "NationalCode")
    protected String nationalCode;

    /**
     * Gets the value of the otherIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfDOIDENTIFIER }
     *     
     */
    public ArrayOfDOIDENTIFIER getOtherIdentifier() {
        return otherIdentifier;
    }

    /**
     * Sets the value of the otherIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfDOIDENTIFIER }
     *     
     */
    public void setOtherIdentifier(ArrayOfDOIDENTIFIER value) {
        this.otherIdentifier = value;
    }

    /**
     * Gets the value of the birthPlaceArea property.
     * 
     * @return
     *     possible object is
     *     {@link HighLevelAreaVO }
     *     
     */
    public HighLevelAreaVO getBirthPlaceArea() {
        return birthPlaceArea;
    }

    /**
     * Sets the value of the birthPlaceArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link HighLevelAreaVO }
     *     
     */
    public void setBirthPlaceArea(HighLevelAreaVO value) {
        this.birthPlaceArea = value;
    }

    /**
     * Gets the value of the religion property.
     * 
     * @return
     *     possible object is
     *     {@link DOCODEDTEXT }
     *     
     */
    public DOCODEDTEXT getReligion() {
        return religion;
    }

    /**
     * Sets the value of the religion property.
     * 
     * @param value
     *     allowed object is
     *     {@link DOCODEDTEXT }
     *     
     */
    public void setReligion(DOCODEDTEXT value) {
        this.religion = value;
    }

    /**
     * Gets the value of the maritalStatus property.
     * 
     * @return
     *     possible object is
     *     {@link DOCODEDTEXT }
     *     
     */
    public DOCODEDTEXT getMaritalStatus() {
        return maritalStatus;
    }

    /**
     * Sets the value of the maritalStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link DOCODEDTEXT }
     *     
     */
    public void setMaritalStatus(DOCODEDTEXT value) {
        this.maritalStatus = value;
    }

    /**
     * Gets the value of the nationality property.
     * 
     * @return
     *     possible object is
     *     {@link DOCODEDTEXT }
     *     
     */
    public DOCODEDTEXT getNationality() {
        return nationality;
    }

    /**
     * Sets the value of the nationality property.
     * 
     * @param value
     *     allowed object is
     *     {@link DOCODEDTEXT }
     *     
     */
    public void setNationality(DOCODEDTEXT value) {
        this.nationality = value;
    }

    /**
     * Gets the value of the birthDate property.
     * 
     * @return
     *     possible object is
     *     {@link DODATE }
     *     
     */
    public DODATE getBirthDate() {
        return birthDate;
    }

    /**
     * Sets the value of the birthDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DODATE }
     *     
     */
    public void setBirthDate(DODATE value) {
        this.birthDate = value;
    }

    /**
     * Gets the value of the birthTime property.
     * 
     * @return
     *     possible object is
     *     {@link DOTIME }
     *     
     */
    public DOTIME getBirthTime() {
        return birthTime;
    }

    /**
     * Sets the value of the birthTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link DOTIME }
     *     
     */
    public void setBirthTime(DOTIME value) {
        this.birthTime = value;
    }

    /**
     * Gets the value of the birthdateAccuracy property.
     * 
     * @return
     *     possible object is
     *     {@link DOCODEDTEXT }
     *     
     */
    public DOCODEDTEXT getBirthdateAccuracy() {
        return birthdateAccuracy;
    }

    /**
     * Sets the value of the birthdateAccuracy property.
     * 
     * @param value
     *     allowed object is
     *     {@link DOCODEDTEXT }
     *     
     */
    public void setBirthdateAccuracy(DOCODEDTEXT value) {
        this.birthdateAccuracy = value;
    }

    /**
     * Gets the value of the fatherFirstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFatherFirstName() {
        return fatherFirstName;
    }

    /**
     * Sets the value of the fatherFirstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFatherFirstName(String value) {
        this.fatherFirstName = value;
    }

    /**
     * Gets the value of the fatherLastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFatherLastName() {
        return fatherLastName;
    }

    /**
     * Sets the value of the fatherLastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFatherLastName(String value) {
        this.fatherLastName = value;
    }

    /**
     * Gets the value of the motherFirstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMotherFirstName() {
        return motherFirstName;
    }

    /**
     * Sets the value of the motherFirstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMotherFirstName(String value) {
        this.motherFirstName = value;
    }

    /**
     * Gets the value of the motherLastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMotherLastName() {
        return motherLastName;
    }

    /**
     * Sets the value of the motherLastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMotherLastName(String value) {
        this.motherLastName = value;
    }

    /**
     * Gets the value of the fullName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * Sets the value of the fullName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFullName(String value) {
        this.fullName = value;
    }

    /**
     * Gets the value of the postalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostalCode() {
        return postalCode;
    }

    /**
     * Sets the value of the postalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostalCode(String value) {
        this.postalCode = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link DOCODEDTEXT }
     *     
     */
    public DOCODEDTEXT getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link DOCODEDTEXT }
     *     
     */
    public void setGender(DOCODEDTEXT value) {
        this.gender = value;
    }

    /**
     * Gets the value of the job property.
     * 
     * @return
     *     possible object is
     *     {@link DOCODEDTEXT }
     *     
     */
    public DOCODEDTEXT getJob() {
        return job;
    }

    /**
     * Sets the value of the job property.
     * 
     * @param value
     *     allowed object is
     *     {@link DOCODEDTEXT }
     *     
     */
    public void setJob(DOCODEDTEXT value) {
        this.job = value;
    }

    /**
     * Gets the value of the jobDescribtion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobDescribtion() {
        return jobDescribtion;
    }

    /**
     * Sets the value of the jobDescribtion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobDescribtion(String value) {
        this.jobDescribtion = value;
    }

    /**
     * Gets the value of the fullAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFullAddress() {
        return fullAddress;
    }

    /**
     * Sets the value of the fullAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFullAddress(String value) {
        this.fullAddress = value;
    }

    /**
     * Gets the value of the livingPlaceArea property.
     * 
     * @return
     *     possible object is
     *     {@link HighLevelAreaVO }
     *     
     */
    public HighLevelAreaVO getLivingPlaceArea() {
        return livingPlaceArea;
    }

    /**
     * Sets the value of the livingPlaceArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link HighLevelAreaVO }
     *     
     */
    public void setLivingPlaceArea(HighLevelAreaVO value) {
        this.livingPlaceArea = value;
    }

    /**
     * Gets the value of the idCardNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDCardNumber() {
        return idCardNumber;
    }

    /**
     * Sets the value of the idCardNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDCardNumber(String value) {
        this.idCardNumber = value;
    }

    /**
     * Gets the value of the idIssueArea property.
     * 
     * @return
     *     possible object is
     *     {@link HighLevelAreaVO }
     *     
     */
    public HighLevelAreaVO getIDIssueArea() {
        return idIssueArea;
    }

    /**
     * Sets the value of the idIssueArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link HighLevelAreaVO }
     *     
     */
    public void setIDIssueArea(HighLevelAreaVO value) {
        this.idIssueArea = value;
    }

    /**
     * Gets the value of the homeTel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHomeTel() {
        return homeTel;
    }

    /**
     * Sets the value of the homeTel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHomeTel(String value) {
        this.homeTel = value;
    }

    /**
     * Gets the value of the mobileNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMobileNumber() {
        return mobileNumber;
    }

    /**
     * Sets the value of the mobileNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMobileNumber(String value) {
        this.mobileNumber = value;
    }

    /**
     * Gets the value of the educationLevel property.
     * 
     * @return
     *     possible object is
     *     {@link DOCODEDTEXT }
     *     
     */
    public DOCODEDTEXT getEducationLevel() {
        return educationLevel;
    }

    /**
     * Sets the value of the educationLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link DOCODEDTEXT }
     *     
     */
    public void setEducationLevel(DOCODEDTEXT value) {
        this.educationLevel = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the nationalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNationalCode() {
        return nationalCode;
    }

    /**
     * Sets the value of the nationalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNationalCode(String value) {
        this.nationalCode = value;
    }

}
