//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.11 at 05:06:35 AM IRDT 
//


package com.asgarie.ClaimSender.entity.ws.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BasicDeathDetailsVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BasicDeathDetailsVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DeathDate" type="{http://thrita.behdasht.gov.ir/VM}DO_DATE" minOccurs="0" form="qualified"/>
 *         &lt;element name="DeathTime" type="{http://thrita.behdasht.gov.ir/VM}DO_TIME" minOccurs="0" form="qualified"/>
 *         &lt;element name="DeathLocation" type="{http://thrita.behdasht.gov.ir/VM}DO_CODED_TEXT" minOccurs="0" form="qualified"/>
 *         &lt;element name="HospitalWard" type="{http://thrita.behdasht.gov.ir/VM}DO_CODED_TEXT" minOccurs="0" form="qualified"/>
 *         &lt;element name="Cause" type="{http://thrita.behdasht.gov.ir/VM}ArrayOfCauseVO" minOccurs="0" form="qualified"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BasicDeathDetailsVO", propOrder = {
    "deathDate",
    "deathTime",
    "deathLocation",
    "hospitalWard",
    "cause"
})
public class BasicDeathDetailsVO {

    @XmlElement(name = "DeathDate")
    protected DODATE deathDate;
    @XmlElement(name = "DeathTime")
    protected DOTIME deathTime;
    @XmlElement(name = "DeathLocation")
    protected DOCODEDTEXT deathLocation;
    @XmlElement(name = "HospitalWard")
    protected DOCODEDTEXT hospitalWard;
    @XmlElement(name = "Cause")
    protected ArrayOfCauseVO cause;

    /**
     * Gets the value of the deathDate property.
     * 
     * @return
     *     possible object is
     *     {@link DODATE }
     *     
     */
    public DODATE getDeathDate() {
        return deathDate;
    }

    /**
     * Sets the value of the deathDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DODATE }
     *     
     */
    public void setDeathDate(DODATE value) {
        this.deathDate = value;
    }

    /**
     * Gets the value of the deathTime property.
     * 
     * @return
     *     possible object is
     *     {@link DOTIME }
     *     
     */
    public DOTIME getDeathTime() {
        return deathTime;
    }

    /**
     * Sets the value of the deathTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link DOTIME }
     *     
     */
    public void setDeathTime(DOTIME value) {
        this.deathTime = value;
    }

    /**
     * Gets the value of the deathLocation property.
     * 
     * @return
     *     possible object is
     *     {@link DOCODEDTEXT }
     *     
     */
    public DOCODEDTEXT getDeathLocation() {
        return deathLocation;
    }

    /**
     * Sets the value of the deathLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link DOCODEDTEXT }
     *     
     */
    public void setDeathLocation(DOCODEDTEXT value) {
        this.deathLocation = value;
    }

    /**
     * Gets the value of the hospitalWard property.
     * 
     * @return
     *     possible object is
     *     {@link DOCODEDTEXT }
     *     
     */
    public DOCODEDTEXT getHospitalWard() {
        return hospitalWard;
    }

    /**
     * Sets the value of the hospitalWard property.
     * 
     * @param value
     *     allowed object is
     *     {@link DOCODEDTEXT }
     *     
     */
    public void setHospitalWard(DOCODEDTEXT value) {
        this.hospitalWard = value;
    }

    /**
     * Gets the value of the cause property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfCauseVO }
     *     
     */
    public ArrayOfCauseVO getCause() {
        return cause;
    }

    /**
     * Sets the value of the cause property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfCauseVO }
     *     
     */
    public void setCause(ArrayOfCauseVO value) {
        this.cause = value;
    }

}
