//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.11 at 05:06:35 AM IRDT 
//


package com.asgarie.ClaimSender.entity.ws.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InsuranceVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InsuranceVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Insurer" type="{http://thrita.behdasht.gov.ir/VM}DO_CODED_TEXT" minOccurs="0" form="qualified"/>
 *         &lt;element name="InsuranceBox" type="{http://thrita.behdasht.gov.ir/VM}DO_CODED_TEXT" minOccurs="0" form="qualified"/>
 *         &lt;element name="InsuranceBookletSerialNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0" form="qualified"/>
 *         &lt;element name="InsuranceExpirationDate" type="{http://thrita.behdasht.gov.ir/VM}DO_DATE" minOccurs="0" form="qualified"/>
 *         &lt;element name="InsuredNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0" form="qualified"/>
 *         &lt;element name="SHEBAD" type="{http://thrita.behdasht.gov.ir/VM}DO_IDENTIFIER" minOccurs="0" form="qualified"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InsuranceVO", propOrder = {
    "insurer",
    "insuranceBox",
    "insuranceBookletSerialNumber",
    "insuranceExpirationDate",
    "insuredNumber",
    "shebad"
})
public class InsuranceVO {

    @XmlElement(name = "Insurer")
    protected DOCODEDTEXT insurer;
    @XmlElement(name = "InsuranceBox")
    protected DOCODEDTEXT insuranceBox;
    @XmlElement(name = "InsuranceBookletSerialNumber")
    protected String insuranceBookletSerialNumber;
    @XmlElement(name = "InsuranceExpirationDate")
    protected DODATE insuranceExpirationDate;
    @XmlElement(name = "InsuredNumber")
    protected String insuredNumber;
    @XmlElement(name = "SHEBAD")
    protected DOIDENTIFIER shebad;

    /**
     * Gets the value of the insurer property.
     * 
     * @return
     *     possible object is
     *     {@link DOCODEDTEXT }
     *     
     */
    public DOCODEDTEXT getInsurer() {
        return insurer;
    }

    /**
     * Sets the value of the insurer property.
     * 
     * @param value
     *     allowed object is
     *     {@link DOCODEDTEXT }
     *     
     */
    public void setInsurer(DOCODEDTEXT value) {
        this.insurer = value;
    }

    /**
     * Gets the value of the insuranceBox property.
     * 
     * @return
     *     possible object is
     *     {@link DOCODEDTEXT }
     *     
     */
    public DOCODEDTEXT getInsuranceBox() {
        return insuranceBox;
    }

    /**
     * Sets the value of the insuranceBox property.
     * 
     * @param value
     *     allowed object is
     *     {@link DOCODEDTEXT }
     *     
     */
    public void setInsuranceBox(DOCODEDTEXT value) {
        this.insuranceBox = value;
    }

    /**
     * Gets the value of the insuranceBookletSerialNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInsuranceBookletSerialNumber() {
        return insuranceBookletSerialNumber;
    }

    /**
     * Sets the value of the insuranceBookletSerialNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInsuranceBookletSerialNumber(String value) {
        this.insuranceBookletSerialNumber = value;
    }

    /**
     * Gets the value of the insuranceExpirationDate property.
     * 
     * @return
     *     possible object is
     *     {@link DODATE }
     *     
     */
    public DODATE getInsuranceExpirationDate() {
        return insuranceExpirationDate;
    }

    /**
     * Sets the value of the insuranceExpirationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DODATE }
     *     
     */
    public void setInsuranceExpirationDate(DODATE value) {
        this.insuranceExpirationDate = value;
    }

    /**
     * Gets the value of the insuredNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInsuredNumber() {
        return insuredNumber;
    }

    /**
     * Sets the value of the insuredNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInsuredNumber(String value) {
        this.insuredNumber = value;
    }

    /**
     * Gets the value of the shebad property.
     * 
     * @return
     *     possible object is
     *     {@link DOIDENTIFIER }
     *     
     */
    public DOIDENTIFIER getSHEBAD() {
        return shebad;
    }

    /**
     * Sets the value of the shebad property.
     * 
     * @param value
     *     allowed object is
     *     {@link DOIDENTIFIER }
     *     
     */
    public void setSHEBAD(DOIDENTIFIER value) {
        this.shebad = value;
    }

}
