//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.11 at 05:06:35 AM IRDT 
//


package ir.demisco.model.entity.request;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ir.demisco.model.entity.request package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ir.demisco.model.entity.request
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SavePatientBill }
     * 
     */
    public SavePatientBill createSavePatientBill() {
        return new SavePatientBill();
    }

    /**
     * Create an instance of {@link PatientBillMessageVO }
     * 
     */
    public PatientBillMessageVO createPatientBillMessageVO() {
        return new PatientBillMessageVO();
    }

    /**
     * Create an instance of {@link ServiceDetailsVO }
     * 
     */
    public ServiceDetailsVO createServiceDetailsVO() {
        return new ServiceDetailsVO();
    }

    /**
     * Create an instance of {@link InsuranceVO }
     * 
     */
    public InsuranceVO createInsuranceVO() {
        return new InsuranceVO();
    }

    /**
     * Create an instance of {@link AdmissionVO }
     * 
     */
    public AdmissionVO createAdmissionVO() {
        return new AdmissionVO();
    }

    /**
     * Create an instance of {@link OrganizationVO }
     * 
     */
    public OrganizationVO createOrganizationVO() {
        return new OrganizationVO();
    }

    /**
     * Create an instance of {@link DiagnosisVO }
     * 
     */
    public DiagnosisVO createDiagnosisVO() {
        return new DiagnosisVO();
    }

    /**
     * Create an instance of {@link BillPatientCompositionVO }
     * 
     */
    public BillPatientCompositionVO createBillPatientCompositionVO() {
        return new BillPatientCompositionVO();
    }

    /**
     * Create an instance of {@link ArrayOfInsuranceVO }
     * 
     */
    public ArrayOfInsuranceVO createArrayOfInsuranceVO() {
        return new ArrayOfInsuranceVO();
    }

    /**
     * Create an instance of {@link DateTimePointVO }
     * 
     */
    public DateTimePointVO createDateTimePointVO() {
        return new DateTimePointVO();
    }

    /**
     * Create an instance of {@link HospitalWardVO }
     * 
     */
    public HospitalWardVO createHospitalWardVO() {
        return new HospitalWardVO();
    }

    /**
     * Create an instance of {@link ServiceGroupRowVO }
     * 
     */
    public ServiceGroupRowVO createServiceGroupRowVO() {
        return new ServiceGroupRowVO();
    }

    /**
     * Create an instance of {@link ArrayOfDiagnosisVO }
     * 
     */
    public ArrayOfDiagnosisVO createArrayOfDiagnosisVO() {
        return new ArrayOfDiagnosisVO();
    }

    /**
     * Create an instance of {@link QuantitiesVO }
     * 
     */
    public QuantitiesVO createQuantitiesVO() {
        return new QuantitiesVO();
    }

    /**
     * Create an instance of {@link DOORDINAL }
     * 
     */
    public DOORDINAL createDOORDINAL() {
        return new DOORDINAL();
    }

    /**
     * Create an instance of {@link DOTIME }
     * 
     */
    public DOTIME createDOTIME() {
        return new DOTIME();
    }

    /**
     * Create an instance of {@link HighLevelAreaVO }
     * 
     */
    public HighLevelAreaVO createHighLevelAreaVO() {
        return new HighLevelAreaVO();
    }

    /**
     * Create an instance of {@link HealthcareProviderVO }
     * 
     */
    public HealthcareProviderVO createHealthcareProviderVO() {
        return new HealthcareProviderVO();
    }

    /**
     * Create an instance of {@link DOQUANTITY }
     * 
     */
    public DOQUANTITY createDOQUANTITY() {
        return new DOQUANTITY();
    }

    /**
     * Create an instance of {@link ArrayOfServiceDetailsVO }
     * 
     */
    public ArrayOfServiceDetailsVO createArrayOfServiceDetailsVO() {
        return new ArrayOfServiceDetailsVO();
    }

    /**
     * Create an instance of {@link MessageIdentifierVO }
     * 
     */
    public MessageIdentifierVO createMessageIdentifierVO() {
        return new MessageIdentifierVO();
    }

    /**
     * Create an instance of {@link ArrayOfQuantitiesVO }
     * 
     */
    public ArrayOfQuantitiesVO createArrayOfQuantitiesVO() {
        return new ArrayOfQuantitiesVO();
    }

    /**
     * Create an instance of {@link RelativeCostVO }
     * 
     */
    public RelativeCostVO createRelativeCostVO() {
        return new RelativeCostVO();
    }

    /**
     * Create an instance of {@link PersonInfoVO }
     * 
     */
    public PersonInfoVO createPersonInfoVO() {
        return new PersonInfoVO();
    }

    /**
     * Create an instance of {@link ArrayOfDOIDENTIFIER }
     * 
     */
    public ArrayOfDOIDENTIFIER createArrayOfDOIDENTIFIER() {
        return new ArrayOfDOIDENTIFIER();
    }

    /**
     * Create an instance of {@link ArrayOfDateTimePointVO }
     * 
     */
    public ArrayOfDateTimePointVO createArrayOfDateTimePointVO() {
        return new ArrayOfDateTimePointVO();
    }

    /**
     * Create an instance of {@link ArrayOfServiceGroupRowVO }
     * 
     */
    public ArrayOfServiceGroupRowVO createArrayOfServiceGroupRowVO() {
        return new ArrayOfServiceGroupRowVO();
    }

    /**
     * Create an instance of {@link CauseVO }
     * 
     */
    public CauseVO createCauseVO() {
        return new CauseVO();
    }

    /**
     * Create an instance of {@link DOIDENTIFIER }
     * 
     */
    public DOIDENTIFIER createDOIDENTIFIER() {
        return new DOIDENTIFIER();
    }

    /**
     * Create an instance of {@link DischargeVO }
     * 
     */
    public DischargeVO createDischargeVO() {
        return new DischargeVO();
    }

    /**
     * Create an instance of {@link BillSummaryVO }
     * 
     */
    public BillSummaryVO createBillSummaryVO() {
        return new BillSummaryVO();
    }

    /**
     * Create an instance of {@link SignatureVO }
     * 
     */
    public SignatureVO createSignatureVO() {
        return new SignatureVO();
    }

    /**
     * Create an instance of {@link DODATE }
     * 
     */
    public DODATE createDODATE() {
        return new DODATE();
    }

    /**
     * Create an instance of {@link ArrayOfCauseVO }
     * 
     */
    public ArrayOfCauseVO createArrayOfCauseVO() {
        return new ArrayOfCauseVO();
    }

    /**
     * Create an instance of {@link DOCODEDTEXT }
     * 
     */
    public DOCODEDTEXT createDOCODEDTEXT() {
        return new DOCODEDTEXT();
    }

    /**
     * Create an instance of {@link ProviderInfoVO }
     * 
     */
    public ProviderInfoVO createProviderInfoVO() {
        return new ProviderInfoVO();
    }

    /**
     * Create an instance of {@link ArrayOfRelativeCostVO }
     * 
     */
    public ArrayOfRelativeCostVO createArrayOfRelativeCostVO() {
        return new ArrayOfRelativeCostVO();
    }

    /**
     * Create an instance of {@link BasicDeathDetailsVO }
     * 
     */
    public BasicDeathDetailsVO createBasicDeathDetailsVO() {
        return new BasicDeathDetailsVO();
    }

}
