//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.11 at 05:06:35 AM IRDT 
//


package com.asgarie.ClaimSender.entity.ws.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PatientBillMessageVO" type="{http://thrita.behdasht.gov.ir/VM}PatientBillMessageVO" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "patientBillMessageVO"
})
@XmlRootElement(name = "SavePatientBill")
public class SavePatientBill {

    @XmlElement(name = "PatientBillMessageVO", namespace = "")
    protected PatientBillMessageVO patientBillMessageVO;

    /**
     * Gets the value of the patientBillMessageVO property.
     * 
     * @return
     *     possible object is
     *     {@link PatientBillMessageVO }
     *     
     */
    public PatientBillMessageVO getPatientBillMessageVO() {
        return patientBillMessageVO;
    }

    /**
     * Sets the value of the patientBillMessageVO property.
     * 
     * @param value
     *     allowed object is
     *     {@link PatientBillMessageVO }
     *     
     */
    public void setPatientBillMessageVO(PatientBillMessageVO value) {
        this.patientBillMessageVO = value;
    }

}
